export type IconEntry = { icon: string; label: string };

export const ICON_CATEGORIES: { label: string; icons: IconEntry[] }[] = [
  {
    label: 'Produce',
    icons: [
      { icon: '🥬', label: 'Greens' },
      { icon: '🥦', label: 'Broccoli' },
      { icon: '🥕', label: 'Carrot' },
      { icon: '🧅', label: 'Onion' },
      { icon: '🧄', label: 'Garlic' },
      { icon: '🥔', label: 'Potato' },
      { icon: '🍅', label: 'Tomato' },
      { icon: '🥒', label: 'Cucumber' },
      { icon: '🫑', label: 'Pepper' },
      { icon: '🌶️', label: 'Chili' },
      { icon: '🥑', label: 'Avocado' },
      { icon: '🌽', label: 'Corn' },
      { icon: '🍄', label: 'Mushroom' },
      { icon: '🥗', label: 'Salad' },
      { icon: '🍎', label: 'Apple' },
      { icon: '🍌', label: 'Banana' },
      { icon: '🍊', label: 'Orange' },
      { icon: '🍋', label: 'Lemon' },
      { icon: '🍇', label: 'Grapes' },
      { icon: '🍓', label: 'Strawberry' },
      { icon: '🫐', label: 'Berries' },
      { icon: '🍉', label: 'Watermelon' },
      { icon: '🍍', label: 'Pineapple' },
      { icon: '🥭', label: 'Mango' },
      { icon: '🍑', label: 'Peach' },
      { icon: '🍐', label: 'Pear' },
      { icon: '🥥', label: 'Coconut' },
      { icon: '🥝', label: 'Kiwi' },
    ],
  },
  {
    label: 'Dairy & eggs',
    icons: [
      { icon: '🥛', label: 'Milk' },
      { icon: '🧀', label: 'Cheese' },
      { icon: '🥚', label: 'Eggs' },
      { icon: '🧈', label: 'Butter' },
      { icon: '🍦', label: 'Yogurt' },
      { icon: '🍨', label: 'Cream' },
    ],
  },
  {
    label: 'Meat & seafood',
    icons: [
      { icon: '🍗', label: 'Chicken' },
      { icon: '🥩', label: 'Meat' },
      { icon: '🥓', label: 'Bacon' },
      { icon: '🌭', label: 'Sausage' },
      { icon: '🐟', label: 'Fish' },
      { icon: '🍤', label: 'Shrimp' },
      { icon: '🦀', label: 'Crab' },
      { icon: '🦐', label: 'Prawns' },
      { icon: '🦑', label: 'Squid' },
    ],
  },
  {
    label: 'Bakery',
    icons: [
      { icon: '🍞', label: 'Bread' },
      { icon: '🥐', label: 'Croissant' },
      { icon: '🥯', label: 'Bagel' },
      { icon: '🧁', label: 'Cupcake' },
      { icon: '🎂', label: 'Cake' },
      { icon: '🥧', label: 'Pie' },
      { icon: '🍪', label: 'Cookies' },
      { icon: '🥨', label: 'Pretzel' },
      { icon: '🫓', label: 'Flatbread' },
      { icon: '🧇', label: 'Waffle' },
      { icon: '🥞', label: 'Pancake' },
    ],
  },
  {
    label: 'Pantry',
    icons: [
      { icon: '🍚', label: 'Rice' },
      { icon: '🍜', label: 'Noodles' },
      { icon: '🍝', label: 'Pasta' },
      { icon: '🫙', label: 'Jar / sauce' },
      { icon: '🍯', label: 'Honey' },
      { icon: '🧂', label: 'Salt' },
      { icon: '🫘', label: 'Beans' },
      { icon: '🌾', label: 'Grains' },
      { icon: '🥜', label: 'Nuts' },
      { icon: '🌰', label: 'Chestnut' },
      { icon: '🍫', label: 'Chocolate' },
      { icon: '🍿', label: 'Popcorn' },
      { icon: '🥫', label: 'Canned food' },
      { icon: '🫒', label: 'Olives' },
      { icon: '🥣', label: 'Cereal' },
      { icon: '🍳', label: 'Cooking oil' },
    ],
  },
  {
    label: 'Beverages',
    icons: [
      { icon: '☕', label: 'Coffee' },
      { icon: '🍵', label: 'Tea' },
      { icon: '🧃', label: 'Juice' },
      { icon: '🥤', label: 'Soda' },
      { icon: '🍷', label: 'Wine' },
      { icon: '🍺', label: 'Beer' },
      { icon: '🥂', label: 'Sparkling' },
      { icon: '💧', label: 'Water' },
    ],
  },
  {
    label: 'Frozen & snacks',
    icons: [
      { icon: '🧊', label: 'Frozen' },
      { icon: '🍕', label: 'Frozen pizza' },
      { icon: '🍦', label: 'Ice cream' },
      { icon: '🍟', label: 'Fries' },
      { icon: '🥟', label: 'Dumplings' },
      { icon: '🍘', label: 'Crackers' },
      { icon: '🍩', label: 'Donut' },
      { icon: '🍬', label: 'Candy' },
    ],
  },
  {
    label: 'Medicine & health',
    icons: [
      { icon: '💊', label: 'Medicine' },
      { icon: '🩹', label: 'Bandage' },
      { icon: '🌡️', label: 'Thermometer' },
      { icon: '💉', label: 'Injection' },
      { icon: '🩺', label: 'First aid' },
      { icon: '😷', label: 'Mask' },
      { icon: '🧬', label: 'Supplement' },
      { icon: '🦠', label: 'Antiseptic' },
      { icon: '🧊', label: 'Ice pack' },
      { icon: '🩸', label: 'Test strips' },
    ],
  },
  {
    label: 'Personal care',
    icons: [
      { icon: '🧴', label: 'Lotion' },
      { icon: '🪥', label: 'Toothbrush' },
      { icon: '🦷', label: 'Toothpaste' },
      { icon: '🧼', label: 'Soap' },
      { icon: '🧽', label: 'Sponge' },
      { icon: '🪒', label: 'Razor' },
      { icon: '💄', label: 'Makeup' },
      { icon: '🧖', label: 'Skincare' },
      { icon: '🧻', label: 'Toilet paper' },
      { icon: '🪮', label: 'Hairbrush' },
      { icon: '💇', label: 'Haircut' },
      { icon: '💅', label: 'Nails' },
    ],
  },
  {
    label: 'Baby & kids',
    icons: [
      { icon: '🍼', label: 'Formula' },
      { icon: '🧷', label: 'Diapers' },
      { icon: '🧸', label: 'Toy' },
      { icon: '👶', label: 'Baby wipes' },
    ],
  },
  {
    label: 'Home & chores',
    icons: [
      { icon: '🛏️', label: 'Bedsheets' },
      { icon: '🧺', label: 'Laundry' },
      { icon: '🧹', label: 'Cleaning' },
      { icon: '🪣', label: 'Mop bucket' },
      { icon: '🧯', label: 'Fire safety' },
      { icon: '🚿', label: 'Shower' },
      { icon: '🕯️', label: 'Candle' },
      { icon: '💡', label: 'Lightbulb' },
      { icon: '🔋', label: 'Battery' },
      { icon: '🪴', label: 'Plant' },
      { icon: '🌀', label: 'AC filter' },
      { icon: '🗑️', label: 'Trash' },
      { icon: '🧽', label: 'Dish sponge' },
      { icon: '🕸️', label: 'Cobweb / dusting' },
      { icon: '🪟', label: 'Windows' },
      { icon: '🚪', label: 'Door / locks' },
    ],
  },
  {
    label: 'Kitchen',
    icons: [
      { icon: '🍽️', label: 'Dishes' },
      { icon: '🔪', label: 'Knife sharpening' },
      { icon: '🫗', label: 'Water filter' },
      { icon: '🧊', label: 'Ice tray' },
      { icon: '🍶', label: 'Bottle' },
      { icon: '🥄', label: 'Cutlery' },
    ],
  },
  {
    label: 'Garden & outdoors',
    icons: [
      { icon: '🌱', label: 'Seedling' },
      { icon: '🌷', label: 'Flowers' },
      { icon: '🌻', label: 'Sunflower' },
      { icon: '🍀', label: 'Lawn' },
      { icon: '🪵', label: 'Firewood' },
      { icon: '🧤', label: 'Gardening gloves' },
    ],
  },
  {
    label: 'Pets',
    icons: [
      { icon: '🐾', label: 'Pet care' },
      { icon: '🐶', label: 'Dog' },
      { icon: '🐱', label: 'Cat' },
      { icon: '🐟', label: 'Fish food' },
      { icon: '🦴', label: 'Pet treats' },
      { icon: '🧴', label: 'Pet shampoo' },
    ],
  },
  {
    label: 'Car & garage',
    icons: [
      { icon: '🚗', label: 'Car' },
      { icon: '🛢️', label: 'Oil change' },
      { icon: '🛞', label: 'Tires' },
      { icon: '🔑', label: 'Keys' },
      { icon: '🧯', label: 'Emergency kit' },
      { icon: '🪫', label: 'Car battery' },
    ],
  },
  {
    label: 'Tech & office',
    icons: [
      { icon: '🔋', label: 'Batteries' },
      { icon: '💾', label: 'Backup' },
      { icon: '🖨️', label: 'Ink / toner' },
      { icon: '📄', label: 'Paper' },
      { icon: '✏️', label: 'Stationery' },
      { icon: '📅', label: 'Subscription' },
      { icon: '🪪', label: 'ID / documents' },
      { icon: '🔌', label: 'Charger' },
    ],
  },
  {
    label: 'Other',
    icons: [
      { icon: '📦', label: 'Package' },
      { icon: '🎁', label: 'Gift' },
      { icon: '📝', label: 'Note' },
      { icon: '⭐', label: 'Favorite' },
      { icon: '❓', label: 'Other' },
    ],
  },
];

export const DEFAULT_EXPIRY_ICON = '🥫';
export const DEFAULT_LAST_TIME_ICON = '📝';
